inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable


Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/AbcSize:
  Max: 33

Metrics/BlockLength:
  Max: 51

Metrics/ClassLength:
  Max: 257

Metrics/MethodLength:
  Max: 18


Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/session_helper.rb'

Rails/NotNullColumn:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 180

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production
