# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: Whitelist.
# Whitelist: find_by_sql
Rails/DynamicFindBy:
  Exclude:
    - 'app/controllers/sessions_controller.rb'
    - 'test/models/student_test.rb'

# Offense count: 2
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/HasManyOrHasOneDependent:
  Exclude:
    - 'app/models/lesson.rb'
    - 'app/models/stage.rb'

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/models/term.rb'

