version: '3'
services:
  db:
    container_name: db
    image: mariadb:10.3
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
      TZ: "Asia/Tokyo"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
  mailer:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
